version: '3.1'
services:
  etcd:
    image: "quay.io/coreos/etcd:v3.4.10"
    entrypoint: /usr/local/bin/etcd
    restart: always
    command:
      - "--name=etcd"
      - "--data-dir=/etcd_data"
      - "--initial-advertise-peer-urls=http://${ETCD_EXTERN_HOST}:2380"
      - "--listen-peer-urls=http://0.0.0.0:2380"
      - "--listen-client-urls=http://0.0.0.0:2379"
      - "--advertise-client-urls=http://${ETCD_EXTERN_HOST}:2379"
      - "--initial-cluster-token=dev etcd" # 节点的token值
      - "--heartbeat-interval=250"
      - "--election-timeout=1250"
      - "--initial-cluster=etcd=http://${ETCD_EXTERN_HOST}:2380"
      - "--initial-cluster-state=new"
    ports:
      - ${ETCD_EXTERN_CLIENT_PORT}:2379
    volumes:
      - ${ETCD_EXTERN_PATH}:/etcd_data
