version: '3'

services:
  emq:
    image: emqx/emqx:4.3.2
    container_name: emqx
    ports:
      - "18083:18083" #后台访问端口 admin/public
      - "1883:1883" #MQTT 协议端口
      - "8084:8084"
      - "8883:8883" #MQTT/SSL 端口
      - "8083:8083" #MQTT/WebSocket 端口