version: '3.1'
services:
  mysql_master:
    image: mysql:5.7.9 # GeneratedColumn
    restart: always
    container_name: mysql_master
    volumes:
#      - ${MYSQL_MASTER_EXTERN_PATH}:/var/lib/mysql  # mac映射到宿主机会报错
      - ./mysql/my.cnf:/etc/mysql/my.cnf
#      - ./mysql/sql_source:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_MASTER_EXTERN_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: hiDronedb2020. #root初始密码 hiDrone12#!
      TZ: Asia/Shanghai
    networks:
      - hidrone_env

  # 定时执行数据库备份
#  mysql_backup:
#    image: bighuangbee1/mysql_backup
#    container_name: mysql_backup
#    restart: always
#    stdin_open: true
#    tty: true
##    environment: #crontab无法读取环境变量，需要在脚本内修改
##      - DB_USER="root"
##      - DB_PASSWD="123456"
##      - DB_HOST="172.17.0.1"
##      - DB_PORT="23306"
##      - DB_NAME="hidrone"
#    volumes:
#      - /data/hidrone/mysql_backup/:/data/mysql_backup/
#      - ./mysql_backup/script/:/root/mysql_backup/
#    networks:
#      - hidrone_env

  redis_master:
    image: redis:6.0
    container_name: redis_master
    restart: always
    ports:
      - ${REDIS_MASTER_EXTERN_PORT}:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ${REDIS_MASTER_EXTERN_PATH}:/data
    command:
      redis-server /usr/local/etc/redis/redis.conf --requirepass hiDronedb2020.
    networks:
      - hidrone_env


networks:
  hidrone_env:
    external:
      name: hidrone_net
